// Generated by npm run icons:generate. Do not edit by hand.
import icon0 from 'pixelarticons/svg/a-arrow-down.svg?url';
import icon1 from 'pixelarticons/svg/a-arrow-down-sharp.svg?url';
import icon2 from 'pixelarticons/svg/a-arrow-up.svg?url';
import icon3 from 'pixelarticons/svg/a-arrow-up-sharp.svg?url';
import icon4 from 'pixelarticons/svg/ai-app-mac.svg?url';
import icon5 from 'pixelarticons/svg/ai-app-mac-sharp.svg?url';
import icon6 from 'pixelarticons/svg/ai-file.svg?url';
import icon7 from 'pixelarticons/svg/ai-file-sharp.svg?url';
import icon8 from 'pixelarticons/svg/ai-scan.svg?url';
import icon9 from 'pixelarticons/svg/ai-scan-sharp.svg?url';
import icon10 from 'pixelarticons/svg/ai-settings-2.svg?url';
import icon11 from 'pixelarticons/svg/ai-settings-3.svg?url';
import icon12 from 'pixelarticons/svg/ai-user-circle.svg?url';
import icon13 from 'pixelarticons/svg/ai-view.svg?url';
import icon14 from 'pixelarticons/svg/ai-voice.svg?url';
import icon15 from 'pixelarticons/svg/ai-voice-sharp.svg?url';
import icon16 from 'pixelarticons/svg/airplay.svg?url';
import icon17 from 'pixelarticons/svg/airplay-sharp.svg?url';
import icon18 from 'pixelarticons/svg/alarm-clock.svg?url';
import icon19 from 'pixelarticons/svg/album.svg?url';
import icon20 from 'pixelarticons/svg/album-sharp.svg?url';
import icon21 from 'pixelarticons/svg/algorithm.svg?url';
import icon22 from 'pixelarticons/svg/algorithm-sharp.svg?url';
import icon23 from 'pixelarticons/svg/alien.svg?url';
import icon24 from 'pixelarticons/svg/align-center-horizontal.svg?url';
import icon25 from 'pixelarticons/svg/align-center-horizontal-sharp.svg?url';
import icon26 from 'pixelarticons/svg/align-center-vertical.svg?url';
import icon27 from 'pixelarticons/svg/align-center-vertical-sharp.svg?url';
import icon28 from 'pixelarticons/svg/align-end-horizontal.svg?url';
import icon29 from 'pixelarticons/svg/align-end-horizontal-sharp.svg?url';
import icon30 from 'pixelarticons/svg/align-end-vertical.svg?url';
import icon31 from 'pixelarticons/svg/align-end-vertical-sharp.svg?url';
import icon32 from 'pixelarticons/svg/align-horizontal-distribute-center.svg?url';
import icon33 from 'pixelarticons/svg/align-horizontal-distribute-center-sharp.svg?url';
import icon34 from 'pixelarticons/svg/align-horizontal-distribute-end.svg?url';
import icon35 from 'pixelarticons/svg/align-horizontal-distribute-end-sharp.svg?url';
import icon36 from 'pixelarticons/svg/align-horizontal-distribute-start.svg?url';
import icon37 from 'pixelarticons/svg/align-horizontal-distribute-start-sharp.svg?url';
import icon38 from 'pixelarticons/svg/align-horizontal-justify-center.svg?url';
import icon39 from 'pixelarticons/svg/align-horizontal-justify-center-sharp.svg?url';
import icon40 from 'pixelarticons/svg/align-horizontal-justify-end.svg?url';
import icon41 from 'pixelarticons/svg/align-horizontal-justify-end-sharp.svg?url';
import icon42 from 'pixelarticons/svg/align-horizontal-justify-start.svg?url';
import icon43 from 'pixelarticons/svg/align-horizontal-justify-start-sharp.svg?url';
import icon44 from 'pixelarticons/svg/align-horizontal-space-around.svg?url';
import icon45 from 'pixelarticons/svg/align-horizontal-space-around-sharp.svg?url';
import icon46 from 'pixelarticons/svg/align-horizontal-space-between.svg?url';
import icon47 from 'pixelarticons/svg/align-horizontal-space-between-sharp.svg?url';
import icon48 from 'pixelarticons/svg/align-start-horizontal.svg?url';
import icon49 from 'pixelarticons/svg/align-start-horizontal-sharp.svg?url';
import icon50 from 'pixelarticons/svg/align-start-vertical.svg?url';
import icon51 from 'pixelarticons/svg/align-start-vertical-sharp.svg?url';
import icon52 from 'pixelarticons/svg/align-vertical-distribute-center.svg?url';
import icon53 from 'pixelarticons/svg/align-vertical-distribute-center-sharp.svg?url';
import icon54 from 'pixelarticons/svg/align-vertical-distribute-end.svg?url';
import icon55 from 'pixelarticons/svg/align-vertical-distribute-end-sharp.svg?url';
import icon56 from 'pixelarticons/svg/align-vertical-distribute-start.svg?url';
import icon57 from 'pixelarticons/svg/align-vertical-distribute-start-sharp.svg?url';
import icon58 from 'pixelarticons/svg/align-vertical-justify-center.svg?url';
import icon59 from 'pixelarticons/svg/align-vertical-justify-center-sharp.svg?url';
import icon60 from 'pixelarticons/svg/align-vertical-justify-end.svg?url';
import icon61 from 'pixelarticons/svg/align-vertical-justify-end-sharp.svg?url';
import icon62 from 'pixelarticons/svg/align-vertical-justify-start.svg?url';
import icon63 from 'pixelarticons/svg/align-vertical-justify-start-sharp.svg?url';
import icon64 from 'pixelarticons/svg/align-vertical-space-around.svg?url';
import icon65 from 'pixelarticons/svg/align-vertical-space-around-sharp.svg?url';
import icon66 from 'pixelarticons/svg/align-vertical-space-between.svg?url';
import icon67 from 'pixelarticons/svg/align-vertical-space-between-sharp.svg?url';
import icon68 from 'pixelarticons/svg/ampersand.svg?url';
import icon69 from 'pixelarticons/svg/ampersand-sharp.svg?url';
import icon70 from 'pixelarticons/svg/analytics.svg?url';
import icon71 from 'pixelarticons/svg/analytics-sharp.svg?url';
import icon72 from 'pixelarticons/svg/anchor.svg?url';
import icon73 from 'pixelarticons/svg/anchor-sharp.svg?url';
import icon74 from 'pixelarticons/svg/angry.svg?url';
import icon75 from 'pixelarticons/svg/angry-sharp.svg?url';
import icon76 from 'pixelarticons/svg/annoyed.svg?url';
import icon77 from 'pixelarticons/svg/annoyed-sharp.svg?url';
import icon78 from 'pixelarticons/svg/app-mac.svg?url';
import icon79 from 'pixelarticons/svg/app-mac-sharp.svg?url';
import icon80 from 'pixelarticons/svg/app-windows.svg?url';
import icon81 from 'pixelarticons/svg/app-windows-sharp.svg?url';
import icon82 from 'pixelarticons/svg/archive.svg?url';
import icon83 from 'pixelarticons/svg/archive-sharp.svg?url';
import icon84 from 'pixelarticons/svg/arrow-bar-down.svg?url';
import icon85 from 'pixelarticons/svg/arrow-bar-left.svg?url';
import icon86 from 'pixelarticons/svg/arrow-bar-right.svg?url';
import icon87 from 'pixelarticons/svg/arrow-bar-up.svg?url';
import icon88 from 'pixelarticons/svg/arrow-big-down.svg?url';
import icon89 from 'pixelarticons/svg/arrow-big-down-dash.svg?url';
import icon90 from 'pixelarticons/svg/arrow-big-down-dash-sharp.svg?url';
import icon91 from 'pixelarticons/svg/arrow-big-down-sharp.svg?url';
import icon92 from 'pixelarticons/svg/arrow-big-up.svg?url';
import icon93 from 'pixelarticons/svg/arrow-big-up-dash.svg?url';
import icon94 from 'pixelarticons/svg/arrow-big-up-dash-sharp.svg?url';
import icon95 from 'pixelarticons/svg/arrow-big-up-sharp.svg?url';
import icon96 from 'pixelarticons/svg/arrow-down.svg?url';
import icon97 from 'pixelarticons/svg/arrow-down-box.svg?url';
import icon98 from 'pixelarticons/svg/arrow-down-box-sharp.svg?url';
import icon99 from 'pixelarticons/svg/arrow-down-circle.svg?url';
import icon100 from 'pixelarticons/svg/arrow-down-diamond.svg?url';
import icon101 from 'pixelarticons/svg/arrow-down-narrow-wide.svg?url';
import icon102 from 'pixelarticons/svg/arrow-down-wide-narrow.svg?url';
import icon103 from 'pixelarticons/svg/arrow-down-z-a.svg?url';
import icon104 from 'pixelarticons/svg/arrow-down-z-a-sharp.svg?url';
import icon105 from 'pixelarticons/svg/arrow-left.svg?url';
import icon106 from 'pixelarticons/svg/arrow-left-box.svg?url';
import icon107 from 'pixelarticons/svg/arrow-left-box-sharp.svg?url';
import icon108 from 'pixelarticons/svg/arrow-right.svg?url';
import icon109 from 'pixelarticons/svg/arrow-right-box.svg?url';
import icon110 from 'pixelarticons/svg/arrow-right-box-sharp.svg?url';
import icon111 from 'pixelarticons/svg/arrow-up.svg?url';
import icon112 from 'pixelarticons/svg/arrow-up-box.svg?url';
import icon113 from 'pixelarticons/svg/arrow-up-box-sharp.svg?url';
import icon114 from 'pixelarticons/svg/arrow-up-narrow-wide.svg?url';
import icon115 from 'pixelarticons/svg/arrow-up-wide-narrow.svg?url';
import icon116 from 'pixelarticons/svg/arrow-up-z-a.svg?url';
import icon117 from 'pixelarticons/svg/arrow-up-z-a-sharp.svg?url';
import icon118 from 'pixelarticons/svg/arrows-horizontal.svg?url';
import icon119 from 'pixelarticons/svg/arrows-vertical.svg?url';
import icon120 from 'pixelarticons/svg/article.svg?url';
import icon121 from 'pixelarticons/svg/article-sharp.svg?url';
import icon122 from 'pixelarticons/svg/aspect-ratio.svg?url';
import icon123 from 'pixelarticons/svg/aspect-ratio-sharp.svg?url';
import icon124 from 'pixelarticons/svg/at-sign.svg?url';
import icon125 from 'pixelarticons/svg/at-sign-sharp.svg?url';
import icon126 from 'pixelarticons/svg/attachment.svg?url';
import icon127 from 'pixelarticons/svg/attachment-sharp.svg?url';
import icon128 from 'pixelarticons/svg/audio-waveform.svg?url';
import icon129 from 'pixelarticons/svg/audio-waveform-sharp.svg?url';
import icon130 from 'pixelarticons/svg/avatar-circle.svg?url';
import icon131 from 'pixelarticons/svg/avatar-circle-minus.svg?url';
import icon132 from 'pixelarticons/svg/avatar-circle-minus-sharp.svg?url';
import icon133 from 'pixelarticons/svg/avatar-circle-plus.svg?url';
import icon134 from 'pixelarticons/svg/avatar-circle-plus-sharp.svg?url';
import icon135 from 'pixelarticons/svg/avatar-circle-sharp.svg?url';
import icon136 from 'pixelarticons/svg/avatar-circle-x.svg?url';
import icon137 from 'pixelarticons/svg/avatar-circle-x-sharp.svg?url';
import icon138 from 'pixelarticons/svg/avatar-square.svg?url';
import icon139 from 'pixelarticons/svg/avatar-square-minus.svg?url';
import icon140 from 'pixelarticons/svg/avatar-square-minus-sharp.svg?url';
import icon141 from 'pixelarticons/svg/avatar-square-plus.svg?url';
import icon142 from 'pixelarticons/svg/avatar-square-plus-sharp.svg?url';
import icon143 from 'pixelarticons/svg/avatar-square-sharp.svg?url';
import icon144 from 'pixelarticons/svg/avatar-square-x.svg?url';
import icon145 from 'pixelarticons/svg/avatar-square-x-sharp.svg?url';
import icon146 from 'pixelarticons/svg/backpack.svg?url';
import icon147 from 'pixelarticons/svg/backpack-sharp.svg?url';
import icon148 from 'pixelarticons/svg/badge-4k.svg?url';
import icon149 from 'pixelarticons/svg/badge-4k-sharp.svg?url';
import icon150 from 'pixelarticons/svg/badge-5k.svg?url';
import icon151 from 'pixelarticons/svg/badge-5k-sharp.svg?url';
import icon152 from 'pixelarticons/svg/badge-captions.svg?url';
import icon153 from 'pixelarticons/svg/badge-captions-sharp.svg?url';
import icon154 from 'pixelarticons/svg/badge-hd.svg?url';
import icon155 from 'pixelarticons/svg/badge-hd-sharp.svg?url';
import icon156 from 'pixelarticons/svg/balloon.svg?url';
import icon157 from 'pixelarticons/svg/banknote.svg?url';
import icon158 from 'pixelarticons/svg/banknote-sharp.svg?url';
import icon159 from 'pixelarticons/svg/barcode.svg?url';
import icon160 from 'pixelarticons/svg/battery.svg?url';
import icon161 from 'pixelarticons/svg/battery-full.svg?url';
import icon162 from 'pixelarticons/svg/battery-full-sharp.svg?url';
import icon163 from 'pixelarticons/svg/battery-low.svg?url';
import icon164 from 'pixelarticons/svg/battery-low-sharp.svg?url';
import icon165 from 'pixelarticons/svg/battery-medium.svg?url';
import icon166 from 'pixelarticons/svg/battery-medium-sharp.svg?url';
import icon167 from 'pixelarticons/svg/battery-sharp.svg?url';
import icon168 from 'pixelarticons/svg/bed.svg?url';
import icon169 from 'pixelarticons/svg/bed-sharp.svg?url';
import icon170 from 'pixelarticons/svg/bell.svg?url';
import icon171 from 'pixelarticons/svg/bell-off.svg?url';
import icon172 from 'pixelarticons/svg/bell-off-sharp.svg?url';
import icon173 from 'pixelarticons/svg/bell-ring.svg?url';
import icon174 from 'pixelarticons/svg/bell-ring-sharp.svg?url';
import icon175 from 'pixelarticons/svg/bell-sharp.svg?url';
import icon176 from 'pixelarticons/svg/binary.svg?url';
import icon177 from 'pixelarticons/svg/binary-sharp.svg?url';
import icon178 from 'pixelarticons/svg/blocks.svg?url';
import icon179 from 'pixelarticons/svg/blocks-sharp.svg?url';
import icon180 from 'pixelarticons/svg/book-open.svg?url';
import icon181 from 'pixelarticons/svg/book-open-sharp.svg?url';
import icon182 from 'pixelarticons/svg/bookmark.svg?url';
import icon183 from 'pixelarticons/svg/bookmark-sharp.svg?url';
import icon184 from 'pixelarticons/svg/bottle-wine.svg?url';
import icon185 from 'pixelarticons/svg/bottle-wine-sharp.svg?url';
import icon186 from 'pixelarticons/svg/box.svg?url';
import icon187 from 'pixelarticons/svg/braces.svg?url';
import icon188 from 'pixelarticons/svg/braces-content.svg?url';
import icon189 from 'pixelarticons/svg/braces-content-sharp.svg?url';
import icon190 from 'pixelarticons/svg/braces-off.svg?url';
import icon191 from 'pixelarticons/svg/braces-off-sharp.svg?url';
import icon192 from 'pixelarticons/svg/braces-sharp.svg?url';
import icon193 from 'pixelarticons/svg/brackets.svg?url';
import icon194 from 'pixelarticons/svg/brackets-angle.svg?url';
import icon195 from 'pixelarticons/svg/brackets-angle-off.svg?url';
import icon196 from 'pixelarticons/svg/brackets-content.svg?url';
import icon197 from 'pixelarticons/svg/brackets-content-sharp.svg?url';
import icon198 from 'pixelarticons/svg/brackets-off.svg?url';
import icon199 from 'pixelarticons/svg/brackets-off-sharp.svg?url';
import icon200 from 'pixelarticons/svg/brackets-sharp.svg?url';
import icon201 from 'pixelarticons/svg/briefcase.svg?url';
import icon202 from 'pixelarticons/svg/briefcase-sharp.svg?url';
import icon203 from 'pixelarticons/svg/briefcases.svg?url';
import icon204 from 'pixelarticons/svg/briefcases-sharp.svg?url';
import icon205 from 'pixelarticons/svg/brush.svg?url';
import icon206 from 'pixelarticons/svg/brush-sharp.svg?url';
import icon207 from 'pixelarticons/svg/bug.svg?url';
import icon208 from 'pixelarticons/svg/bug-sharp.svg?url';
import icon209 from 'pixelarticons/svg/building.svg?url';
import icon210 from 'pixelarticons/svg/building-community.svg?url';
import icon211 from 'pixelarticons/svg/building-community-sharp.svg?url';
import icon212 from 'pixelarticons/svg/building-sharp.svg?url';
import icon213 from 'pixelarticons/svg/bulletlist.svg?url';
import icon214 from 'pixelarticons/svg/bulletlist-sharp.svg?url';
import icon215 from 'pixelarticons/svg/bus.svg?url';
import icon216 from 'pixelarticons/svg/bus-sharp.svg?url';
import icon217 from 'pixelarticons/svg/cake.svg?url';
import icon218 from 'pixelarticons/svg/cake-sharp.svg?url';
import icon219 from 'pixelarticons/svg/calculator.svg?url';
import icon220 from 'pixelarticons/svg/calculator-sharp.svg?url';
import icon221 from 'pixelarticons/svg/calendar.svg?url';
import icon222 from 'pixelarticons/svg/calendar-2.svg?url';
import icon223 from 'pixelarticons/svg/calendar-2-sharp.svg?url';
import icon224 from 'pixelarticons/svg/calendar-range.svg?url';
import icon225 from 'pixelarticons/svg/calendar-range-sharp.svg?url';
import icon226 from 'pixelarticons/svg/calendar-sharp.svg?url';
import icon227 from 'pixelarticons/svg/calendar-text.svg?url';
import icon228 from 'pixelarticons/svg/calendar-text-sharp.svg?url';
import icon229 from 'pixelarticons/svg/calendar-weeks.svg?url';
import icon230 from 'pixelarticons/svg/calendar-weeks-sharp.svg?url';
import icon231 from 'pixelarticons/svg/camera.svg?url';
import icon232 from 'pixelarticons/svg/camera-sharp.svg?url';
import icon233 from 'pixelarticons/svg/cancel.svg?url';
import icon234 from 'pixelarticons/svg/car.svg?url';
import icon235 from 'pixelarticons/svg/car-sharp.svg?url';
import icon236 from 'pixelarticons/svg/card.svg?url';
import icon237 from 'pixelarticons/svg/card-sharp.svg?url';
import icon238 from 'pixelarticons/svg/card-text.svg?url';
import icon239 from 'pixelarticons/svg/card-text-sharp.svg?url';
import icon240 from 'pixelarticons/svg/castle.svg?url';
import icon241 from 'pixelarticons/svg/castle-sharp.svg?url';
import icon242 from 'pixelarticons/svg/cellular-signal-0.svg?url';
import icon243 from 'pixelarticons/svg/cellular-signal-0-sharp.svg?url';
import icon244 from 'pixelarticons/svg/cellular-signal-1.svg?url';
import icon245 from 'pixelarticons/svg/cellular-signal-1-sharp.svg?url';
import icon246 from 'pixelarticons/svg/cellular-signal-2.svg?url';
import icon247 from 'pixelarticons/svg/cellular-signal-2-sharp.svg?url';
import icon248 from 'pixelarticons/svg/cellular-signal-3.svg?url';
import icon249 from 'pixelarticons/svg/cellular-signal-3-sharp.svg?url';
import icon250 from 'pixelarticons/svg/chart.svg?url';
import icon251 from 'pixelarticons/svg/chart-bar-big.svg?url';
import icon252 from 'pixelarticons/svg/chart-bar-big-sharp.svg?url';
import icon253 from 'pixelarticons/svg/chart-column-decreasing.svg?url';
import icon254 from 'pixelarticons/svg/chart-column-decreasing-sharp.svg?url';
import icon255 from 'pixelarticons/svg/chart-sharp.svg?url';
import icon256 from 'pixelarticons/svg/check.svg?url';
import icon257 from 'pixelarticons/svg/check-double.svg?url';
import icon258 from 'pixelarticons/svg/checkbox.svg?url';
import icon259 from 'pixelarticons/svg/checkbox-on.svg?url';
import icon260 from 'pixelarticons/svg/checkbox-on-sharp.svg?url';
import icon261 from 'pixelarticons/svg/checkbox-sharp.svg?url';
import icon262 from 'pixelarticons/svg/chess.svg?url';
import icon263 from 'pixelarticons/svg/chess-sharp.svg?url';
import icon264 from 'pixelarticons/svg/chevron-down.svg?url';
import icon265 from 'pixelarticons/svg/chevron-down-2.svg?url';
import icon266 from 'pixelarticons/svg/chevron-left.svg?url';
import icon267 from 'pixelarticons/svg/chevron-left-2.svg?url';
import icon268 from 'pixelarticons/svg/chevron-right.svg?url';
import icon269 from 'pixelarticons/svg/chevron-right-2.svg?url';
import icon270 from 'pixelarticons/svg/chevron-up.svg?url';
import icon271 from 'pixelarticons/svg/chevron-up-2.svg?url';
import icon272 from 'pixelarticons/svg/chevrons-horizontal.svg?url';
import icon273 from 'pixelarticons/svg/chevrons-horizontal-2.svg?url';
import icon274 from 'pixelarticons/svg/chevrons-vertical.svg?url';
import icon275 from 'pixelarticons/svg/chevrons-vertical-2.svg?url';
import icon276 from 'pixelarticons/svg/cigarette-off.svg?url';
import icon277 from 'pixelarticons/svg/cigarette-off-sharp.svg?url';
import icon278 from 'pixelarticons/svg/circle.svg?url';
import icon279 from 'pixelarticons/svg/circle-pile.svg?url';
import icon280 from 'pixelarticons/svg/circle-power.svg?url';
import icon281 from 'pixelarticons/svg/circle-square.svg?url';
import icon282 from 'pixelarticons/svg/circuit-board.svg?url';
import icon283 from 'pixelarticons/svg/circuit-board-sharp.svg?url';
import icon284 from 'pixelarticons/svg/clapperboard.svg?url';
import icon285 from 'pixelarticons/svg/clapperboard-sharp.svg?url';
import icon286 from 'pixelarticons/svg/clipboard.svg?url';
import icon287 from 'pixelarticons/svg/clipboard-note.svg?url';
import icon288 from 'pixelarticons/svg/clipboard-note-sharp.svg?url';
import icon289 from 'pixelarticons/svg/clipboard-sharp.svg?url';
import icon290 from 'pixelarticons/svg/clock.svg?url';
import icon291 from 'pixelarticons/svg/close.svg?url';
import icon292 from 'pixelarticons/svg/cloud.svg?url';
import icon293 from 'pixelarticons/svg/cloud-moon.svg?url';
import icon294 from 'pixelarticons/svg/cloud-server.svg?url';
import icon295 from 'pixelarticons/svg/cloud-sun.svg?url';
import icon296 from 'pixelarticons/svg/coffee.svg?url';
import icon297 from 'pixelarticons/svg/coffee-sharp.svg?url';
import icon298 from 'pixelarticons/svg/coins.svg?url';
import icon299 from 'pixelarticons/svg/colors-swatch.svg?url';
import icon300 from 'pixelarticons/svg/colors-swatch-sharp.svg?url';
import icon301 from 'pixelarticons/svg/comment.svg?url';
import icon302 from 'pixelarticons/svg/comment-sharp.svg?url';
import icon303 from 'pixelarticons/svg/comment-text.svg?url';
import icon304 from 'pixelarticons/svg/comment-text-sharp.svg?url';
import icon305 from 'pixelarticons/svg/computer.svg?url';
import icon306 from 'pixelarticons/svg/computer-sharp.svg?url';
import icon307 from 'pixelarticons/svg/contact.svg?url';
import icon308 from 'pixelarticons/svg/contact-sharp.svg?url';
import icon309 from 'pixelarticons/svg/copy.svg?url';
import icon310 from 'pixelarticons/svg/copy-sharp.svg?url';
import icon311 from 'pixelarticons/svg/copy-x.svg?url';
import icon312 from 'pixelarticons/svg/copy-x-sharp.svg?url';
import icon313 from 'pixelarticons/svg/corner-down-left.svg?url';
import icon314 from 'pixelarticons/svg/corner-down-left-sharp.svg?url';
import icon315 from 'pixelarticons/svg/corner-down-right.svg?url';
import icon316 from 'pixelarticons/svg/corner-down-right-sharp.svg?url';
import icon317 from 'pixelarticons/svg/corner-left-down.svg?url';
import icon318 from 'pixelarticons/svg/corner-left-down-sharp.svg?url';
import icon319 from 'pixelarticons/svg/corner-left-up.svg?url';
import icon320 from 'pixelarticons/svg/corner-left-up-sharp.svg?url';
import icon321 from 'pixelarticons/svg/corner-right-down.svg?url';
import icon322 from 'pixelarticons/svg/corner-right-down-sharp.svg?url';
import icon323 from 'pixelarticons/svg/corner-right-up.svg?url';
import icon324 from 'pixelarticons/svg/corner-right-up-sharp.svg?url';
import icon325 from 'pixelarticons/svg/corner-up-left.svg?url';
import icon326 from 'pixelarticons/svg/corner-up-left-sharp.svg?url';
import icon327 from 'pixelarticons/svg/corner-up-right.svg?url';
import icon328 from 'pixelarticons/svg/corner-up-right-sharp.svg?url';
import icon329 from 'pixelarticons/svg/cpu.svg?url';
import icon330 from 'pixelarticons/svg/cpu-sharp.svg?url';
import icon331 from 'pixelarticons/svg/credit-card.svg?url';
import icon332 from 'pixelarticons/svg/credit-card-sharp.svg?url';
import icon333 from 'pixelarticons/svg/crown.svg?url';
import icon334 from 'pixelarticons/svg/crown-sharp.svg?url';
import icon335 from 'pixelarticons/svg/cursor-minimal.svg?url';
import icon336 from 'pixelarticons/svg/cut.svg?url';
import icon337 from 'pixelarticons/svg/cut-sharp.svg?url';
import icon338 from 'pixelarticons/svg/database.svg?url';
import icon339 from 'pixelarticons/svg/date-time.svg?url';
import icon340 from 'pixelarticons/svg/debug.svg?url';
import icon341 from 'pixelarticons/svg/delete.svg?url';
import icon342 from 'pixelarticons/svg/delete-sharp.svg?url';
import icon343 from 'pixelarticons/svg/diamond-gem.svg?url';
import icon344 from 'pixelarticons/svg/directions.svg?url';
import icon345 from 'pixelarticons/svg/directions-sharp.svg?url';
import icon346 from 'pixelarticons/svg/dock.svg?url';
import icon347 from 'pixelarticons/svg/dock-sharp.svg?url';
import icon348 from 'pixelarticons/svg/dog.svg?url';
import icon349 from 'pixelarticons/svg/door-closed.svg?url';
import icon350 from 'pixelarticons/svg/door-closed-sharp.svg?url';
import icon351 from 'pixelarticons/svg/download.svg?url';
import icon352 from 'pixelarticons/svg/download-sharp.svg?url';
import icon353 from 'pixelarticons/svg/drum.svg?url';
import icon354 from 'pixelarticons/svg/earth.svg?url';
import icon355 from 'pixelarticons/svg/estate.svg?url';
import icon356 from 'pixelarticons/svg/estate-sharp.svg?url';
import icon357 from 'pixelarticons/svg/expand.svg?url';
import icon358 from 'pixelarticons/svg/external-link.svg?url';
import icon359 from 'pixelarticons/svg/external-link-sharp.svg?url';
import icon360 from 'pixelarticons/svg/eye.svg?url';
import icon361 from 'pixelarticons/svg/eye-off.svg?url';
import icon362 from 'pixelarticons/svg/factory.svg?url';
import icon363 from 'pixelarticons/svg/factory-sharp.svg?url';
import icon364 from 'pixelarticons/svg/feather.svg?url';
import icon365 from 'pixelarticons/svg/file.svg?url';
import icon366 from 'pixelarticons/svg/file-sharp.svg?url';
import icon367 from 'pixelarticons/svg/file-text.svg?url';
import icon368 from 'pixelarticons/svg/file-text-sharp.svg?url';
import icon369 from 'pixelarticons/svg/files.svg?url';
import icon370 from 'pixelarticons/svg/files-sharp.svg?url';
import icon371 from 'pixelarticons/svg/filter.svg?url';
import icon372 from 'pixelarticons/svg/fire.svg?url';
import icon373 from 'pixelarticons/svg/fish.svg?url';
import icon374 from 'pixelarticons/svg/flag.svg?url';
import icon375 from 'pixelarticons/svg/flatten.svg?url';
import icon376 from 'pixelarticons/svg/flip-horizontal-2.svg?url';
import icon377 from 'pixelarticons/svg/flip-vertical-2.svg?url';
import icon378 from 'pixelarticons/svg/float-center.svg?url';
import icon379 from 'pixelarticons/svg/float-center-sharp.svg?url';
import icon380 from 'pixelarticons/svg/float-left.svg?url';
import icon381 from 'pixelarticons/svg/float-left-sharp.svg?url';
import icon382 from 'pixelarticons/svg/float-right.svg?url';
import icon383 from 'pixelarticons/svg/float-right-sharp.svg?url';
import icon384 from 'pixelarticons/svg/folder.svg?url';
import icon385 from 'pixelarticons/svg/folder-plus.svg?url';
import icon386 from 'pixelarticons/svg/folder-plus-sharp.svg?url';
import icon387 from 'pixelarticons/svg/folder-sharp.svg?url';
import icon388 from 'pixelarticons/svg/forward.svg?url';
import icon389 from 'pixelarticons/svg/forward-sharp.svg?url';
import icon390 from 'pixelarticons/svg/frame.svg?url';
import icon391 from 'pixelarticons/svg/frown.svg?url';
import icon392 from 'pixelarticons/svg/gallery-thumbnails.svg?url';
import icon393 from 'pixelarticons/svg/gallery-thumbnails-sharp.svg?url';
import icon394 from 'pixelarticons/svg/gamepad.svg?url';
import icon395 from 'pixelarticons/svg/gamepad-sharp.svg?url';
import icon396 from 'pixelarticons/svg/gift.svg?url';
import icon397 from 'pixelarticons/svg/gift-sharp.svg?url';
import icon398 from 'pixelarticons/svg/git-branch.svg?url';
import icon399 from 'pixelarticons/svg/git-branch-sharp.svg?url';
import icon400 from 'pixelarticons/svg/git-commit.svg?url';
import icon401 from 'pixelarticons/svg/git-commit-sharp.svg?url';
import icon402 from 'pixelarticons/svg/git-merge.svg?url';
import icon403 from 'pixelarticons/svg/git-merge-sharp.svg?url';
import icon404 from 'pixelarticons/svg/git-pull-request.svg?url';
import icon405 from 'pixelarticons/svg/git-pull-request-sharp.svg?url';
import icon406 from 'pixelarticons/svg/globe.svg?url';
import icon407 from 'pixelarticons/svg/goal.svg?url';
import icon408 from 'pixelarticons/svg/gps.svg?url';
import icon409 from 'pixelarticons/svg/gps-2.svg?url';
import icon410 from 'pixelarticons/svg/gps-2-sharp.svg?url';
import icon411 from 'pixelarticons/svg/gps-sharp.svg?url';
import icon412 from 'pixelarticons/svg/gpu.svg?url';
import icon413 from 'pixelarticons/svg/gpu-sharp.svg?url';
import icon414 from 'pixelarticons/svg/grid-2x2-2.svg?url';
import icon415 from 'pixelarticons/svg/grid-2x2-2-sharp.svg?url';
import icon416 from 'pixelarticons/svg/grid-2x3.svg?url';
import icon417 from 'pixelarticons/svg/grid-2x3-sharp.svg?url';
import icon418 from 'pixelarticons/svg/grid-3x2.svg?url';
import icon419 from 'pixelarticons/svg/grid-3x2-sharp.svg?url';
import icon420 from 'pixelarticons/svg/grid-3x3.svg?url';
import icon421 from 'pixelarticons/svg/grid-3x3-sharp.svg?url';
import icon422 from 'pixelarticons/svg/hand.svg?url';
import icon423 from 'pixelarticons/svg/handbag.svg?url';
import icon424 from 'pixelarticons/svg/handbag-sharp.svg?url';
import icon425 from 'pixelarticons/svg/hash.svg?url';
import icon426 from 'pixelarticons/svg/heading.svg?url';
import icon427 from 'pixelarticons/svg/heading-1.svg?url';
import icon428 from 'pixelarticons/svg/heading-2.svg?url';
import icon429 from 'pixelarticons/svg/heading-3.svg?url';
import icon430 from 'pixelarticons/svg/heading-4.svg?url';
import icon431 from 'pixelarticons/svg/heading-5.svg?url';
import icon432 from 'pixelarticons/svg/heading-6.svg?url';
import icon433 from 'pixelarticons/svg/headphone.svg?url';
import icon434 from 'pixelarticons/svg/heart.svg?url';
import icon435 from 'pixelarticons/svg/helicopter.svg?url';
import icon436 from 'pixelarticons/svg/home.svg?url';
import icon437 from 'pixelarticons/svg/home-sharp.svg?url';
import icon438 from 'pixelarticons/svg/hotel-bed.svg?url';
import icon439 from 'pixelarticons/svg/hotel-bed-sharp.svg?url';
import icon440 from 'pixelarticons/svg/human.svg?url';
import icon441 from 'pixelarticons/svg/human-arms-down.svg?url';
import icon442 from 'pixelarticons/svg/human-arms-up.svg?url';
import icon443 from 'pixelarticons/svg/icon-category.svg?url';
import icon444 from 'pixelarticons/svg/icons.svg?url';
import icon445 from 'pixelarticons/svg/image.svg?url';
import icon446 from 'pixelarticons/svg/image-2-plus.svg?url';
import icon447 from 'pixelarticons/svg/image-2-plus-sharp.svg?url';
import icon448 from 'pixelarticons/svg/image-new.svg?url';
import icon449 from 'pixelarticons/svg/image-new-sharp.svg?url';
import icon450 from 'pixelarticons/svg/image-sharp.svg?url';
import icon451 from 'pixelarticons/svg/images.svg?url';
import icon452 from 'pixelarticons/svg/images-sharp.svg?url';
import icon453 from 'pixelarticons/svg/inbox.svg?url';
import icon454 from 'pixelarticons/svg/inbox-sharp.svg?url';
import icon455 from 'pixelarticons/svg/info-box.svg?url';
import icon456 from 'pixelarticons/svg/info-box-sharp.svg?url';
import icon457 from 'pixelarticons/svg/invert.svg?url';
import icon458 from 'pixelarticons/svg/invert-sharp.svg?url';
import icon459 from 'pixelarticons/svg/invoice.svg?url';
import icon460 from 'pixelarticons/svg/invoice-sharp.svg?url';
import icon461 from 'pixelarticons/svg/joystick.svg?url';
import icon462 from 'pixelarticons/svg/joystick-sharp.svg?url';
import icon463 from 'pixelarticons/svg/keyboard-music.svg?url';
import icon464 from 'pixelarticons/svg/keyboard-music-sharp.svg?url';
import icon465 from 'pixelarticons/svg/languages.svg?url';
import icon466 from 'pixelarticons/svg/languages-sharp.svg?url';
import icon467 from 'pixelarticons/svg/lasso.svg?url';
import icon468 from 'pixelarticons/svg/laugh.svg?url';
import icon469 from 'pixelarticons/svg/laugh-sharp.svg?url';
import icon470 from 'pixelarticons/svg/leaf.svg?url';
import icon471 from 'pixelarticons/svg/letter-a.svg?url';
import icon472 from 'pixelarticons/svg/letter-a-circle.svg?url';
import icon473 from 'pixelarticons/svg/letter-b.svg?url';
import icon474 from 'pixelarticons/svg/letter-b-circle.svg?url';
import icon475 from 'pixelarticons/svg/letter-c.svg?url';
import icon476 from 'pixelarticons/svg/letter-c-circle.svg?url';
import icon477 from 'pixelarticons/svg/letter-d.svg?url';
import icon478 from 'pixelarticons/svg/letter-d-circle.svg?url';
import icon479 from 'pixelarticons/svg/letter-e.svg?url';
import icon480 from 'pixelarticons/svg/letter-e-circle.svg?url';
import icon481 from 'pixelarticons/svg/letter-f.svg?url';
import icon482 from 'pixelarticons/svg/letter-f-circle.svg?url';
import icon483 from 'pixelarticons/svg/letter-g.svg?url';
import icon484 from 'pixelarticons/svg/letter-g-circle.svg?url';
import icon485 from 'pixelarticons/svg/letter-h.svg?url';
import icon486 from 'pixelarticons/svg/letter-h-circle.svg?url';
import icon487 from 'pixelarticons/svg/letter-i.svg?url';
import icon488 from 'pixelarticons/svg/letter-i-circle.svg?url';
import icon489 from 'pixelarticons/svg/letter-j.svg?url';
import icon490 from 'pixelarticons/svg/letter-j-circle.svg?url';
import icon491 from 'pixelarticons/svg/letter-k.svg?url';
import icon492 from 'pixelarticons/svg/letter-k-circle.svg?url';
import icon493 from 'pixelarticons/svg/letter-l.svg?url';
import icon494 from 'pixelarticons/svg/letter-l-circle.svg?url';
import icon495 from 'pixelarticons/svg/letter-m.svg?url';
import icon496 from 'pixelarticons/svg/letter-m-circle.svg?url';
import icon497 from 'pixelarticons/svg/letter-n.svg?url';
import icon498 from 'pixelarticons/svg/letter-n-circle.svg?url';
import icon499 from 'pixelarticons/svg/letter-o.svg?url';
import icon500 from 'pixelarticons/svg/letter-o-circle.svg?url';
import icon501 from 'pixelarticons/svg/letter-p.svg?url';
import icon502 from 'pixelarticons/svg/letter-p-circle.svg?url';
import icon503 from 'pixelarticons/svg/letter-q.svg?url';
import icon504 from 'pixelarticons/svg/letter-q-circle.svg?url';
import icon505 from 'pixelarticons/svg/letter-r.svg?url';
import icon506 from 'pixelarticons/svg/letter-r-circle.svg?url';
import icon507 from 'pixelarticons/svg/letter-s.svg?url';
import icon508 from 'pixelarticons/svg/letter-s-circle.svg?url';
import icon509 from 'pixelarticons/svg/letter-t.svg?url';
import icon510 from 'pixelarticons/svg/letter-t-circle.svg?url';
import icon511 from 'pixelarticons/svg/letter-u.svg?url';
import icon512 from 'pixelarticons/svg/letter-u-circle.svg?url';
import icon513 from 'pixelarticons/svg/letter-v.svg?url';
import icon514 from 'pixelarticons/svg/letter-v-circle.svg?url';
import icon515 from 'pixelarticons/svg/letter-w.svg?url';
import icon516 from 'pixelarticons/svg/letter-w-circle.svg?url';
import icon517 from 'pixelarticons/svg/letter-x.svg?url';
import icon518 from 'pixelarticons/svg/letter-x-circle.svg?url';
import icon519 from 'pixelarticons/svg/letter-y.svg?url';
import icon520 from 'pixelarticons/svg/letter-y-circle.svg?url';
import icon521 from 'pixelarticons/svg/letter-z.svg?url';
import icon522 from 'pixelarticons/svg/letter-z-circle.svg?url';
import icon523 from 'pixelarticons/svg/library.svg?url';
import icon524 from 'pixelarticons/svg/lightbulb.svg?url';
import icon525 from 'pixelarticons/svg/lightbulb-off.svg?url';
import icon526 from 'pixelarticons/svg/link.svg?url';
import icon527 from 'pixelarticons/svg/link-sharp.svg?url';
import icon528 from 'pixelarticons/svg/list-box.svg?url';
import icon529 from 'pixelarticons/svg/list-box-sharp.svg?url';
import icon530 from 'pixelarticons/svg/loader.svg?url';
import icon531 from 'pixelarticons/svg/loading.svg?url';
import icon532 from 'pixelarticons/svg/loading-2.svg?url';
import icon533 from 'pixelarticons/svg/loading-3.svg?url';
import icon534 from 'pixelarticons/svg/lock.svg?url';
import icon535 from 'pixelarticons/svg/lock-sharp.svg?url';
import icon536 from 'pixelarticons/svg/login.svg?url';
import icon537 from 'pixelarticons/svg/login-sharp.svg?url';
import icon538 from 'pixelarticons/svg/logout.svg?url';
import icon539 from 'pixelarticons/svg/logout-sharp.svg?url';
import icon540 from 'pixelarticons/svg/magic-edit.svg?url';
import icon541 from 'pixelarticons/svg/mail.svg?url';
import icon542 from 'pixelarticons/svg/mail-open.svg?url';
import icon543 from 'pixelarticons/svg/mail-open-sharp.svg?url';
import icon544 from 'pixelarticons/svg/mail-right.svg?url';
import icon545 from 'pixelarticons/svg/mail-right-sharp.svg?url';
import icon546 from 'pixelarticons/svg/mail-sharp.svg?url';
import icon547 from 'pixelarticons/svg/mailbox.svg?url';
import icon548 from 'pixelarticons/svg/mailbox-sharp.svg?url';
import icon549 from 'pixelarticons/svg/map-pin.svg?url';
import icon550 from 'pixelarticons/svg/map-pin-home.svg?url';
import icon551 from 'pixelarticons/svg/megaphone.svg?url';
import icon552 from 'pixelarticons/svg/megaphone-sharp.svg?url';
import icon553 from 'pixelarticons/svg/meh.svg?url';
import icon554 from 'pixelarticons/svg/meh-sharp.svg?url';
import icon555 from 'pixelarticons/svg/membercard.svg?url';
import icon556 from 'pixelarticons/svg/membercard-sharp.svg?url';
import icon557 from 'pixelarticons/svg/memory-stick.svg?url';
import icon558 from 'pixelarticons/svg/memory-stick-sharp.svg?url';
import icon559 from 'pixelarticons/svg/menu.svg?url';
import icon560 from 'pixelarticons/svg/menu-circle.svg?url';
import icon561 from 'pixelarticons/svg/menu-square.svg?url';
import icon562 from 'pixelarticons/svg/menu-square-sharp.svg?url';
import icon563 from 'pixelarticons/svg/message.svg?url';
import icon564 from 'pixelarticons/svg/message-sharp.svg?url';
import icon565 from 'pixelarticons/svg/message-text.svg?url';
import icon566 from 'pixelarticons/svg/message-text-sharp.svg?url';
import icon567 from 'pixelarticons/svg/mic.svg?url';
import icon568 from 'pixelarticons/svg/mic-off.svg?url';
import icon569 from 'pixelarticons/svg/mic-off-sharp.svg?url';
import icon570 from 'pixelarticons/svg/mic-sharp.svg?url';
import icon571 from 'pixelarticons/svg/minus.svg?url';
import icon572 from 'pixelarticons/svg/minus-box.svg?url';
import icon573 from 'pixelarticons/svg/minus-box-sharp.svg?url';
import icon574 from 'pixelarticons/svg/modem.svg?url';
import icon575 from 'pixelarticons/svg/modem-sharp.svg?url';
import icon576 from 'pixelarticons/svg/money.svg?url';
import icon577 from 'pixelarticons/svg/money-sharp.svg?url';
import icon578 from 'pixelarticons/svg/monitor.svg?url';
import icon579 from 'pixelarticons/svg/monitor-sharp.svg?url';
import icon580 from 'pixelarticons/svg/moon.svg?url';
import icon581 from 'pixelarticons/svg/more-horizontal.svg?url';
import icon582 from 'pixelarticons/svg/more-horizontal-sharp.svg?url';
import icon583 from 'pixelarticons/svg/more-vertical.svg?url';
import icon584 from 'pixelarticons/svg/more-vertical-sharp.svg?url';
import icon585 from 'pixelarticons/svg/mouse.svg?url';
import icon586 from 'pixelarticons/svg/music.svg?url';
import icon587 from 'pixelarticons/svg/music-sharp.svg?url';
import icon588 from 'pixelarticons/svg/note.svg?url';
import icon589 from 'pixelarticons/svg/note-sharp.svg?url';
import icon590 from 'pixelarticons/svg/notebook.svg?url';
import icon591 from 'pixelarticons/svg/notebook-sharp.svg?url';
import icon592 from 'pixelarticons/svg/notes.svg?url';
import icon593 from 'pixelarticons/svg/notes-sharp.svg?url';
import icon594 from 'pixelarticons/svg/open.svg?url';
import icon595 from 'pixelarticons/svg/open-sharp.svg?url';
import icon596 from 'pixelarticons/svg/package.svg?url';
import icon597 from 'pixelarticons/svg/parking.svg?url';
import icon598 from 'pixelarticons/svg/parking-off.svg?url';
import icon599 from 'pixelarticons/svg/parking-off-sharp.svg?url';
import icon600 from 'pixelarticons/svg/parking-sharp.svg?url';
import icon601 from 'pixelarticons/svg/party-popper.svg?url';
import icon602 from 'pixelarticons/svg/pc-case.svg?url';
import icon603 from 'pixelarticons/svg/pc-case-sharp.svg?url';
import icon604 from 'pixelarticons/svg/pen-square.svg?url';
import icon605 from 'pixelarticons/svg/pen-square-sharp.svg?url';
import icon606 from 'pixelarticons/svg/pencil.svg?url';
import icon607 from 'pixelarticons/svg/phone.svg?url';
import icon608 from 'pixelarticons/svg/phone-call.svg?url';
import icon609 from 'pixelarticons/svg/phone-call-sharp.svg?url';
import icon610 from 'pixelarticons/svg/phone-outgoing.svg?url';
import icon611 from 'pixelarticons/svg/phone-outgoing-sharp.svg?url';
import icon612 from 'pixelarticons/svg/phone-sharp.svg?url';
import icon613 from 'pixelarticons/svg/pi.svg?url';
import icon614 from 'pixelarticons/svg/pi-circle.svg?url';
import icon615 from 'pixelarticons/svg/picture-in-picture.svg?url';
import icon616 from 'pixelarticons/svg/picture-in-picture-sharp.svg?url';
import icon617 from 'pixelarticons/svg/pipette.svg?url';
import icon618 from 'pixelarticons/svg/pixelarticons.svg?url';
import icon619 from 'pixelarticons/svg/play.svg?url';
import icon620 from 'pixelarticons/svg/plus.svg?url';
import icon621 from 'pixelarticons/svg/plus-box.svg?url';
import icon622 from 'pixelarticons/svg/plus-box-sharp.svg?url';
import icon623 from 'pixelarticons/svg/pointer.svg?url';
import icon624 from 'pixelarticons/svg/potion.svg?url';
import icon625 from 'pixelarticons/svg/potion-sharp.svg?url';
import icon626 from 'pixelarticons/svg/pound.svg?url';
import icon627 from 'pixelarticons/svg/power.svg?url';
import icon628 from 'pixelarticons/svg/power-off.svg?url';
import icon629 from 'pixelarticons/svg/presentation.svg?url';
import icon630 from 'pixelarticons/svg/presentation-sharp.svg?url';
import icon631 from 'pixelarticons/svg/printer.svg?url';
import icon632 from 'pixelarticons/svg/printer-minimal-sharp.svg?url';
import icon633 from 'pixelarticons/svg/projector.svg?url';
import icon634 from 'pixelarticons/svg/proportions.svg?url';
import icon635 from 'pixelarticons/svg/proportions-sharp.svg?url';
import icon636 from 'pixelarticons/svg/quote-text-inline.svg?url';
import icon637 from 'pixelarticons/svg/radio.svg?url';
import icon638 from 'pixelarticons/svg/radius.svg?url';
import icon639 from 'pixelarticons/svg/ratio.svg?url';
import icon640 from 'pixelarticons/svg/receipt.svg?url';
import icon641 from 'pixelarticons/svg/receipt-sharp.svg?url';
import icon642 from 'pixelarticons/svg/recycle.svg?url';
import icon643 from 'pixelarticons/svg/redo.svg?url';
import icon644 from 'pixelarticons/svg/redo-sharp.svg?url';
import icon645 from 'pixelarticons/svg/reload.svg?url';
import icon646 from 'pixelarticons/svg/reload-sharp.svg?url';
import icon647 from 'pixelarticons/svg/repeat.svg?url';
import icon648 from 'pixelarticons/svg/repeat-sharp.svg?url';
import icon649 from 'pixelarticons/svg/road-sign.svg?url';
import icon650 from 'pixelarticons/svg/robot.svg?url';
import icon651 from 'pixelarticons/svg/robot-face.svg?url';
import icon652 from 'pixelarticons/svg/robot-face-happy.svg?url';
import icon653 from 'pixelarticons/svg/robot-face-happy-sharp.svg?url';
import icon654 from 'pixelarticons/svg/robot-face-sad.svg?url';
import icon655 from 'pixelarticons/svg/robot-face-sad-sharp.svg?url';
import icon656 from 'pixelarticons/svg/robot-face-sharp.svg?url';
import icon657 from 'pixelarticons/svg/robot-sharp.svg?url';
import icon658 from 'pixelarticons/svg/rss.svg?url';
import icon659 from 'pixelarticons/svg/rss-circle.svg?url';
import icon660 from 'pixelarticons/svg/rss-square.svg?url';
import icon661 from 'pixelarticons/svg/rss-square-sharp.svg?url';
import icon662 from 'pixelarticons/svg/rubel.svg?url';
import icon663 from 'pixelarticons/svg/save.svg?url';
import icon664 from 'pixelarticons/svg/save-sharp.svg?url';
import icon665 from 'pixelarticons/svg/scale.svg?url';
import icon666 from 'pixelarticons/svg/scan-barcode.svg?url';
import icon667 from 'pixelarticons/svg/scan-barcode-sharp.svg?url';
import icon668 from 'pixelarticons/svg/scissors.svg?url';
import icon669 from 'pixelarticons/svg/scissors-sharp.svg?url';
import icon670 from 'pixelarticons/svg/script.svg?url';
import icon671 from 'pixelarticons/svg/script-sharp.svg?url';
import icon672 from 'pixelarticons/svg/scroll-horizontal.svg?url';
import icon673 from 'pixelarticons/svg/scroll-vertical.svg?url';
import icon674 from 'pixelarticons/svg/search.svg?url';
import icon675 from 'pixelarticons/svg/section.svg?url';
import icon676 from 'pixelarticons/svg/section-copy.svg?url';
import icon677 from 'pixelarticons/svg/section-minus.svg?url';
import icon678 from 'pixelarticons/svg/section-plus.svg?url';
import icon679 from 'pixelarticons/svg/section-x.svg?url';
import icon680 from 'pixelarticons/svg/send.svg?url';
import icon681 from 'pixelarticons/svg/server.svg?url';
import icon682 from 'pixelarticons/svg/server-sharp.svg?url';
import icon683 from 'pixelarticons/svg/settings-2.svg?url';
import icon684 from 'pixelarticons/svg/settings-2-sharp.svg?url';
import icon685 from 'pixelarticons/svg/settings-cog.svg?url';
import icon686 from 'pixelarticons/svg/settings-cog-2.svg?url';
import icon687 from 'pixelarticons/svg/shapes.svg?url';
import icon688 from 'pixelarticons/svg/share.svg?url';
import icon689 from 'pixelarticons/svg/share-sharp.svg?url';
import icon690 from 'pixelarticons/svg/shield.svg?url';
import icon691 from 'pixelarticons/svg/shield-sharp.svg?url';
import icon692 from 'pixelarticons/svg/ship.svg?url';
import icon693 from 'pixelarticons/svg/shirt.svg?url';
import icon694 from 'pixelarticons/svg/shirt-sharp.svg?url';
import icon695 from 'pixelarticons/svg/shopping-bag.svg?url';
import icon696 from 'pixelarticons/svg/shopping-bag-sharp.svg?url';
import icon697 from 'pixelarticons/svg/shopping-cart.svg?url';
import icon698 from 'pixelarticons/svg/shuffle.svg?url';
import icon699 from 'pixelarticons/svg/shuffle-sharp.svg?url';
import icon700 from 'pixelarticons/svg/signal.svg?url';
import icon701 from 'pixelarticons/svg/siren.svg?url';
import icon702 from 'pixelarticons/svg/siren-off.svg?url';
import icon703 from 'pixelarticons/svg/siren-off-sharp.svg?url';
import icon704 from 'pixelarticons/svg/siren-sharp.svg?url';
import icon705 from 'pixelarticons/svg/skull.svg?url';
import icon706 from 'pixelarticons/svg/skull-sharp.svg?url';
import icon707 from 'pixelarticons/svg/smart-home.svg?url';
import icon708 from 'pixelarticons/svg/smart-home-sharp.svg?url';
import icon709 from 'pixelarticons/svg/smartphone.svg?url';
import icon710 from 'pixelarticons/svg/smartphone-sharp.svg?url';
import icon711 from 'pixelarticons/svg/smile.svg?url';
import icon712 from 'pixelarticons/svg/smile-sharp.svg?url';
import icon713 from 'pixelarticons/svg/snail.svg?url';
import icon714 from 'pixelarticons/svg/snake.svg?url';
import icon715 from 'pixelarticons/svg/sofa.svg?url';
import icon716 from 'pixelarticons/svg/sofa-sharp.svg?url';
import icon717 from 'pixelarticons/svg/sort-horizontal.svg?url';
import icon718 from 'pixelarticons/svg/sort-vertical.svg?url';
import icon719 from 'pixelarticons/svg/sparkle.svg?url';
import icon720 from 'pixelarticons/svg/sparkles.svg?url';
import icon721 from 'pixelarticons/svg/speed-fast.svg?url';
import icon722 from 'pixelarticons/svg/speed-medium.svg?url';
import icon723 from 'pixelarticons/svg/speed-slow.svg?url';
import icon724 from 'pixelarticons/svg/spline-cursor.svg?url';
import icon725 from 'pixelarticons/svg/spotlight.svg?url';
import icon726 from 'pixelarticons/svg/spotlight-sharp.svg?url';
import icon727 from 'pixelarticons/svg/spray.svg?url';
import icon728 from 'pixelarticons/svg/spray-can.svg?url';
import icon729 from 'pixelarticons/svg/spray-image.svg?url';
import icon730 from 'pixelarticons/svg/spray-wave.svg?url';
import icon731 from 'pixelarticons/svg/square.svg?url';
import icon732 from 'pixelarticons/svg/square-alert.svg?url';
import icon733 from 'pixelarticons/svg/square-alert-sharp.svg?url';
import icon734 from 'pixelarticons/svg/square-chevron-down.svg?url';
import icon735 from 'pixelarticons/svg/square-chevron-down-sharp.svg?url';
import icon736 from 'pixelarticons/svg/square-chevron-left.svg?url';
import icon737 from 'pixelarticons/svg/square-chevron-left-sharp.svg?url';
import icon738 from 'pixelarticons/svg/square-chevron-right.svg?url';
import icon739 from 'pixelarticons/svg/square-chevron-right-sharp.svg?url';
import icon740 from 'pixelarticons/svg/square-chevron-up.svg?url';
import icon741 from 'pixelarticons/svg/square-chevron-up-sharp.svg?url';
import icon742 from 'pixelarticons/svg/square-cursor.svg?url';
import icon743 from 'pixelarticons/svg/square-cursor-sharp.svg?url';
import icon744 from 'pixelarticons/svg/square-dashed-cursor.svg?url';
import icon745 from 'pixelarticons/svg/square-dashed-cursor-sharp.svg?url';
import icon746 from 'pixelarticons/svg/square-power.svg?url';
import icon747 from 'pixelarticons/svg/square-power-sharp.svg?url';
import icon748 from 'pixelarticons/svg/square-scissors.svg?url';
import icon749 from 'pixelarticons/svg/square-scissors-sharp.svg?url';
import icon750 from 'pixelarticons/svg/square-sharp.svg?url';
import icon751 from 'pixelarticons/svg/star.svg?url';
import icon752 from 'pixelarticons/svg/sticker.svg?url';
import icon753 from 'pixelarticons/svg/sticker-sharp.svg?url';
import icon754 from 'pixelarticons/svg/sticky-note.svg?url';
import icon755 from 'pixelarticons/svg/sticky-note-sharp.svg?url';
import icon756 from 'pixelarticons/svg/sticky-note-text.svg?url';
import icon757 from 'pixelarticons/svg/sticky-note-text-sharp.svg?url';
import icon758 from 'pixelarticons/svg/store.svg?url';
import icon759 from 'pixelarticons/svg/store-sharp.svg?url';
import icon760 from 'pixelarticons/svg/subscriptions.svg?url';
import icon761 from 'pixelarticons/svg/subscriptions-sharp.svg?url';
import icon762 from 'pixelarticons/svg/suitcase.svg?url';
import icon763 from 'pixelarticons/svg/suitcase-sharp.svg?url';
import icon764 from 'pixelarticons/svg/sunglasses.svg?url';
import icon765 from 'pixelarticons/svg/sunglasses-sharp.svg?url';
import icon766 from 'pixelarticons/svg/switch.svg?url';
import icon767 from 'pixelarticons/svg/sword.svg?url';
import icon768 from 'pixelarticons/svg/t-arrow-down.svg?url';
import icon769 from 'pixelarticons/svg/t-arrow-up.svg?url';
import icon770 from 'pixelarticons/svg/t-rex.svg?url';
import icon771 from 'pixelarticons/svg/tab.svg?url';
import icon772 from 'pixelarticons/svg/tab-sharp.svg?url';
import icon773 from 'pixelarticons/svg/tablet.svg?url';
import icon774 from 'pixelarticons/svg/tablet-sharp.svg?url';
import icon775 from 'pixelarticons/svg/tangent.svg?url';
import icon776 from 'pixelarticons/svg/target.svg?url';
import icon777 from 'pixelarticons/svg/tea.svg?url';
import icon778 from 'pixelarticons/svg/tea-sharp.svg?url';
import icon779 from 'pixelarticons/svg/teach.svg?url';
import icon780 from 'pixelarticons/svg/teach-sharp.svg?url';
import icon781 from 'pixelarticons/svg/tent.svg?url';
import icon782 from 'pixelarticons/svg/terminal.svg?url';
import icon783 from 'pixelarticons/svg/terminal-sharp.svg?url';
import icon784 from 'pixelarticons/svg/test-tube.svg?url';
import icon785 from 'pixelarticons/svg/test-tube-sharp.svg?url';
import icon786 from 'pixelarticons/svg/text-align-center.svg?url';
import icon787 from 'pixelarticons/svg/text-align-center-box.svg?url';
import icon788 from 'pixelarticons/svg/text-align-center-box-sharp.svg?url';
import icon789 from 'pixelarticons/svg/text-align-justify.svg?url';
import icon790 from 'pixelarticons/svg/text-align-justify-box.svg?url';
import icon791 from 'pixelarticons/svg/text-align-justify-box-sharp.svg?url';
import icon792 from 'pixelarticons/svg/text-align-left.svg?url';
import icon793 from 'pixelarticons/svg/text-align-left-box.svg?url';
import icon794 from 'pixelarticons/svg/text-align-left-box-sharp.svg?url';
import icon795 from 'pixelarticons/svg/text-align-right.svg?url';
import icon796 from 'pixelarticons/svg/text-align-right-box.svg?url';
import icon797 from 'pixelarticons/svg/text-align-right-box-sharp.svg?url';
import icon798 from 'pixelarticons/svg/text-colums.svg?url';
import icon799 from 'pixelarticons/svg/text-cursor.svg?url';
import icon800 from 'pixelarticons/svg/text-cursor-input.svg?url';
import icon801 from 'pixelarticons/svg/text-cursor-input-sharp.svg?url';
import icon802 from 'pixelarticons/svg/text-start-a.svg?url';
import icon803 from 'pixelarticons/svg/text-start-a-sharp.svg?url';
import icon804 from 'pixelarticons/svg/text-start-t.svg?url';
import icon805 from 'pixelarticons/svg/text-wrap.svg?url';
import icon806 from 'pixelarticons/svg/text-wrap-sharp.svg?url';
import icon807 from 'pixelarticons/svg/thermometer.svg?url';
import icon808 from 'pixelarticons/svg/thermometer-sharp.svg?url';
import icon809 from 'pixelarticons/svg/thumbs-down.svg?url';
import icon810 from 'pixelarticons/svg/thumbs-down-sharp.svg?url';
import icon811 from 'pixelarticons/svg/thumbs-up.svg?url';
import icon812 from 'pixelarticons/svg/thumbs-up-sharp.svg?url';
import icon813 from 'pixelarticons/svg/toke-circle.svg?url';
import icon814 from 'pixelarticons/svg/toke-square.svg?url';
import icon815 from 'pixelarticons/svg/toke-square-sharp.svg?url';
import icon816 from 'pixelarticons/svg/tool-case.svg?url';
import icon817 from 'pixelarticons/svg/tool-case-sharp.svg?url';
import icon818 from 'pixelarticons/svg/tournament.svg?url';
import icon819 from 'pixelarticons/svg/tournament-sharp.svg?url';
import icon820 from 'pixelarticons/svg/trash.svg?url';
import icon821 from 'pixelarticons/svg/trash-sharp.svg?url';
import icon822 from 'pixelarticons/svg/tree.svg?url';
import icon823 from 'pixelarticons/svg/tree-pine.svg?url';
import icon824 from 'pixelarticons/svg/trophy.svg?url';
import icon825 from 'pixelarticons/svg/trophy-sharp.svg?url';
import icon826 from 'pixelarticons/svg/truck.svg?url';
import icon827 from 'pixelarticons/svg/truck-sharp.svg?url';
import icon828 from 'pixelarticons/svg/tv.svg?url';
import icon829 from 'pixelarticons/svg/tv-sharp.svg?url';
import icon830 from 'pixelarticons/svg/undo.svg?url';
import icon831 from 'pixelarticons/svg/undo-sharp.svg?url';
import icon832 from 'pixelarticons/svg/university.svg?url';
import icon833 from 'pixelarticons/svg/university-sharp.svg?url';
import icon834 from 'pixelarticons/svg/unlink.svg?url';
import icon835 from 'pixelarticons/svg/unlink-sharp.svg?url';
import icon836 from 'pixelarticons/svg/unlock.svg?url';
import icon837 from 'pixelarticons/svg/unlock-sharp.svg?url';
import icon838 from 'pixelarticons/svg/upload.svg?url';
import icon839 from 'pixelarticons/svg/upload-sharp.svg?url';
import icon840 from 'pixelarticons/svg/user.svg?url';
import icon841 from 'pixelarticons/svg/user-minus.svg?url';
import icon842 from 'pixelarticons/svg/user-minus-sharp.svg?url';
import icon843 from 'pixelarticons/svg/user-plus.svg?url';
import icon844 from 'pixelarticons/svg/user-plus-sharp.svg?url';
import icon845 from 'pixelarticons/svg/user-sharp.svg?url';
import icon846 from 'pixelarticons/svg/user-x.svg?url';
import icon847 from 'pixelarticons/svg/user-x-sharp.svg?url';
import icon848 from 'pixelarticons/svg/users.svg?url';
import icon849 from 'pixelarticons/svg/users-sharp.svg?url';
import icon850 from 'pixelarticons/svg/utility-pole.svg?url';
import icon851 from 'pixelarticons/svg/vibrate.svg?url';
import icon852 from 'pixelarticons/svg/vibrate-sharp.svg?url';
import icon853 from 'pixelarticons/svg/video.svg?url';
import icon854 from 'pixelarticons/svg/video-sharp.svg?url';
import icon855 from 'pixelarticons/svg/volume.svg?url';
import icon856 from 'pixelarticons/svg/volume-1.svg?url';
import icon857 from 'pixelarticons/svg/volume-2.svg?url';
import icon858 from 'pixelarticons/svg/volume-3.svg?url';
import icon859 from 'pixelarticons/svg/wall.svg?url';
import icon860 from 'pixelarticons/svg/wall-sharp.svg?url';
import icon861 from 'pixelarticons/svg/wallet.svg?url';
import icon862 from 'pixelarticons/svg/wallet-sharp.svg?url';
import icon863 from 'pixelarticons/svg/warehouse.svg?url';
import icon864 from 'pixelarticons/svg/warning-diamond.svg?url';
import icon865 from 'pixelarticons/svg/waves.svg?url';
import icon866 from 'pixelarticons/svg/waves-arrow-down.svg?url';
import icon867 from 'pixelarticons/svg/waves-arrow-up.svg?url';
import icon868 from 'pixelarticons/svg/webcam.svg?url';
import icon869 from 'pixelarticons/svg/wifi.svg?url';
import icon870 from 'pixelarticons/svg/wind.svg?url';
import icon871 from 'pixelarticons/svg/window-frame.svg?url';
import icon872 from 'pixelarticons/svg/window-frame-sharp.svg?url';
import icon873 from 'pixelarticons/svg/zap.svg?url';
import icon874 from 'pixelarticons/svg/zap-off.svg?url';
import icon875 from 'pixelarticons/svg/zoom-in.svg?url';
import icon876 from 'pixelarticons/svg/zoom-out.svg?url';

import type { IconName } from './icon-names';

export const PIXEL_ICON_ASSETS = {
  "a-arrow-down": icon0,
  "a-arrow-down-sharp": icon1,
  "a-arrow-up": icon2,
  "a-arrow-up-sharp": icon3,
  "ai-app-mac": icon4,
  "ai-app-mac-sharp": icon5,
  "ai-file": icon6,
  "ai-file-sharp": icon7,
  "ai-scan": icon8,
  "ai-scan-sharp": icon9,
  "ai-settings-2": icon10,
  "ai-settings-3": icon11,
  "ai-user-circle": icon12,
  "ai-view": icon13,
  "ai-voice": icon14,
  "ai-voice-sharp": icon15,
  "airplay": icon16,
  "airplay-sharp": icon17,
  "alarm-clock": icon18,
  "album": icon19,
  "album-sharp": icon20,
  "algorithm": icon21,
  "algorithm-sharp": icon22,
  "alien": icon23,
  "align-center-horizontal": icon24,
  "align-center-horizontal-sharp": icon25,
  "align-center-vertical": icon26,
  "align-center-vertical-sharp": icon27,
  "align-end-horizontal": icon28,
  "align-end-horizontal-sharp": icon29,
  "align-end-vertical": icon30,
  "align-end-vertical-sharp": icon31,
  "align-horizontal-distribute-center": icon32,
  "align-horizontal-distribute-center-sharp": icon33,
  "align-horizontal-distribute-end": icon34,
  "align-horizontal-distribute-end-sharp": icon35,
  "align-horizontal-distribute-start": icon36,
  "align-horizontal-distribute-start-sharp": icon37,
  "align-horizontal-justify-center": icon38,
  "align-horizontal-justify-center-sharp": icon39,
  "align-horizontal-justify-end": icon40,
  "align-horizontal-justify-end-sharp": icon41,
  "align-horizontal-justify-start": icon42,
  "align-horizontal-justify-start-sharp": icon43,
  "align-horizontal-space-around": icon44,
  "align-horizontal-space-around-sharp": icon45,
  "align-horizontal-space-between": icon46,
  "align-horizontal-space-between-sharp": icon47,
  "align-start-horizontal": icon48,
  "align-start-horizontal-sharp": icon49,
  "align-start-vertical": icon50,
  "align-start-vertical-sharp": icon51,
  "align-vertical-distribute-center": icon52,
  "align-vertical-distribute-center-sharp": icon53,
  "align-vertical-distribute-end": icon54,
  "align-vertical-distribute-end-sharp": icon55,
  "align-vertical-distribute-start": icon56,
  "align-vertical-distribute-start-sharp": icon57,
  "align-vertical-justify-center": icon58,
  "align-vertical-justify-center-sharp": icon59,
  "align-vertical-justify-end": icon60,
  "align-vertical-justify-end-sharp": icon61,
  "align-vertical-justify-start": icon62,
  "align-vertical-justify-start-sharp": icon63,
  "align-vertical-space-around": icon64,
  "align-vertical-space-around-sharp": icon65,
  "align-vertical-space-between": icon66,
  "align-vertical-space-between-sharp": icon67,
  "ampersand": icon68,
  "ampersand-sharp": icon69,
  "analytics": icon70,
  "analytics-sharp": icon71,
  "anchor": icon72,
  "anchor-sharp": icon73,
  "angry": icon74,
  "angry-sharp": icon75,
  "annoyed": icon76,
  "annoyed-sharp": icon77,
  "app-mac": icon78,
  "app-mac-sharp": icon79,
  "app-windows": icon80,
  "app-windows-sharp": icon81,
  "archive": icon82,
  "archive-sharp": icon83,
  "arrow-bar-down": icon84,
  "arrow-bar-left": icon85,
  "arrow-bar-right": icon86,
  "arrow-bar-up": icon87,
  "arrow-big-down": icon88,
  "arrow-big-down-dash": icon89,
  "arrow-big-down-dash-sharp": icon90,
  "arrow-big-down-sharp": icon91,
  "arrow-big-up": icon92,
  "arrow-big-up-dash": icon93,
  "arrow-big-up-dash-sharp": icon94,
  "arrow-big-up-sharp": icon95,
  "arrow-down": icon96,
  "arrow-down-box": icon97,
  "arrow-down-box-sharp": icon98,
  "arrow-down-circle": icon99,
  "arrow-down-diamond": icon100,
  "arrow-down-narrow-wide": icon101,
  "arrow-down-wide-narrow": icon102,
  "arrow-down-z-a": icon103,
  "arrow-down-z-a-sharp": icon104,
  "arrow-left": icon105,
  "arrow-left-box": icon106,
  "arrow-left-box-sharp": icon107,
  "arrow-right": icon108,
  "arrow-right-box": icon109,
  "arrow-right-box-sharp": icon110,
  "arrow-up": icon111,
  "arrow-up-box": icon112,
  "arrow-up-box-sharp": icon113,
  "arrow-up-narrow-wide": icon114,
  "arrow-up-wide-narrow": icon115,
  "arrow-up-z-a": icon116,
  "arrow-up-z-a-sharp": icon117,
  "arrows-horizontal": icon118,
  "arrows-vertical": icon119,
  "article": icon120,
  "article-sharp": icon121,
  "aspect-ratio": icon122,
  "aspect-ratio-sharp": icon123,
  "at-sign": icon124,
  "at-sign-sharp": icon125,
  "attachment": icon126,
  "attachment-sharp": icon127,
  "audio-waveform": icon128,
  "audio-waveform-sharp": icon129,
  "avatar-circle": icon130,
  "avatar-circle-minus": icon131,
  "avatar-circle-minus-sharp": icon132,
  "avatar-circle-plus": icon133,
  "avatar-circle-plus-sharp": icon134,
  "avatar-circle-sharp": icon135,
  "avatar-circle-x": icon136,
  "avatar-circle-x-sharp": icon137,
  "avatar-square": icon138,
  "avatar-square-minus": icon139,
  "avatar-square-minus-sharp": icon140,
  "avatar-square-plus": icon141,
  "avatar-square-plus-sharp": icon142,
  "avatar-square-sharp": icon143,
  "avatar-square-x": icon144,
  "avatar-square-x-sharp": icon145,
  "backpack": icon146,
  "backpack-sharp": icon147,
  "badge-4k": icon148,
  "badge-4k-sharp": icon149,
  "badge-5k": icon150,
  "badge-5k-sharp": icon151,
  "badge-captions": icon152,
  "badge-captions-sharp": icon153,
  "badge-hd": icon154,
  "badge-hd-sharp": icon155,
  "balloon": icon156,
  "banknote": icon157,
  "banknote-sharp": icon158,
  "barcode": icon159,
  "battery": icon160,
  "battery-full": icon161,
  "battery-full-sharp": icon162,
  "battery-low": icon163,
  "battery-low-sharp": icon164,
  "battery-medium": icon165,
  "battery-medium-sharp": icon166,
  "battery-sharp": icon167,
  "bed": icon168,
  "bed-sharp": icon169,
  "bell": icon170,
  "bell-off": icon171,
  "bell-off-sharp": icon172,
  "bell-ring": icon173,
  "bell-ring-sharp": icon174,
  "bell-sharp": icon175,
  "binary": icon176,
  "binary-sharp": icon177,
  "blocks": icon178,
  "blocks-sharp": icon179,
  "book-open": icon180,
  "book-open-sharp": icon181,
  "bookmark": icon182,
  "bookmark-sharp": icon183,
  "bottle-wine": icon184,
  "bottle-wine-sharp": icon185,
  "box": icon186,
  "braces": icon187,
  "braces-content": icon188,
  "braces-content-sharp": icon189,
  "braces-off": icon190,
  "braces-off-sharp": icon191,
  "braces-sharp": icon192,
  "brackets": icon193,
  "brackets-angle": icon194,
  "brackets-angle-off": icon195,
  "brackets-content": icon196,
  "brackets-content-sharp": icon197,
  "brackets-off": icon198,
  "brackets-off-sharp": icon199,
  "brackets-sharp": icon200,
  "briefcase": icon201,
  "briefcase-sharp": icon202,
  "briefcases": icon203,
  "briefcases-sharp": icon204,
  "brush": icon205,
  "brush-sharp": icon206,
  "bug": icon207,
  "bug-sharp": icon208,
  "building": icon209,
  "building-community": icon210,
  "building-community-sharp": icon211,
  "building-sharp": icon212,
  "bulletlist": icon213,
  "bulletlist-sharp": icon214,
  "bus": icon215,
  "bus-sharp": icon216,
  "cake": icon217,
  "cake-sharp": icon218,
  "calculator": icon219,
  "calculator-sharp": icon220,
  "calendar": icon221,
  "calendar-2": icon222,
  "calendar-2-sharp": icon223,
  "calendar-range": icon224,
  "calendar-range-sharp": icon225,
  "calendar-sharp": icon226,
  "calendar-text": icon227,
  "calendar-text-sharp": icon228,
  "calendar-weeks": icon229,
  "calendar-weeks-sharp": icon230,
  "camera": icon231,
  "camera-sharp": icon232,
  "cancel": icon233,
  "car": icon234,
  "car-sharp": icon235,
  "card": icon236,
  "card-sharp": icon237,
  "card-text": icon238,
  "card-text-sharp": icon239,
  "castle": icon240,
  "castle-sharp": icon241,
  "cellular-signal-0": icon242,
  "cellular-signal-0-sharp": icon243,
  "cellular-signal-1": icon244,
  "cellular-signal-1-sharp": icon245,
  "cellular-signal-2": icon246,
  "cellular-signal-2-sharp": icon247,
  "cellular-signal-3": icon248,
  "cellular-signal-3-sharp": icon249,
  "chart": icon250,
  "chart-bar-big": icon251,
  "chart-bar-big-sharp": icon252,
  "chart-column-decreasing": icon253,
  "chart-column-decreasing-sharp": icon254,
  "chart-sharp": icon255,
  "check": icon256,
  "check-double": icon257,
  "checkbox": icon258,
  "checkbox-on": icon259,
  "checkbox-on-sharp": icon260,
  "checkbox-sharp": icon261,
  "chess": icon262,
  "chess-sharp": icon263,
  "chevron-down": icon264,
  "chevron-down-2": icon265,
  "chevron-left": icon266,
  "chevron-left-2": icon267,
  "chevron-right": icon268,
  "chevron-right-2": icon269,
  "chevron-up": icon270,
  "chevron-up-2": icon271,
  "chevrons-horizontal": icon272,
  "chevrons-horizontal-2": icon273,
  "chevrons-vertical": icon274,
  "chevrons-vertical-2": icon275,
  "cigarette-off": icon276,
  "cigarette-off-sharp": icon277,
  "circle": icon278,
  "circle-pile": icon279,
  "circle-power": icon280,
  "circle-square": icon281,
  "circuit-board": icon282,
  "circuit-board-sharp": icon283,
  "clapperboard": icon284,
  "clapperboard-sharp": icon285,
  "clipboard": icon286,
  "clipboard-note": icon287,
  "clipboard-note-sharp": icon288,
  "clipboard-sharp": icon289,
  "clock": icon290,
  "close": icon291,
  "cloud": icon292,
  "cloud-moon": icon293,
  "cloud-server": icon294,
  "cloud-sun": icon295,
  "coffee": icon296,
  "coffee-sharp": icon297,
  "coins": icon298,
  "colors-swatch": icon299,
  "colors-swatch-sharp": icon300,
  "comment": icon301,
  "comment-sharp": icon302,
  "comment-text": icon303,
  "comment-text-sharp": icon304,
  "computer": icon305,
  "computer-sharp": icon306,
  "contact": icon307,
  "contact-sharp": icon308,
  "copy": icon309,
  "copy-sharp": icon310,
  "copy-x": icon311,
  "copy-x-sharp": icon312,
  "corner-down-left": icon313,
  "corner-down-left-sharp": icon314,
  "corner-down-right": icon315,
  "corner-down-right-sharp": icon316,
  "corner-left-down": icon317,
  "corner-left-down-sharp": icon318,
  "corner-left-up": icon319,
  "corner-left-up-sharp": icon320,
  "corner-right-down": icon321,
  "corner-right-down-sharp": icon322,
  "corner-right-up": icon323,
  "corner-right-up-sharp": icon324,
  "corner-up-left": icon325,
  "corner-up-left-sharp": icon326,
  "corner-up-right": icon327,
  "corner-up-right-sharp": icon328,
  "cpu": icon329,
  "cpu-sharp": icon330,
  "credit-card": icon331,
  "credit-card-sharp": icon332,
  "crown": icon333,
  "crown-sharp": icon334,
  "cursor-minimal": icon335,
  "cut": icon336,
  "cut-sharp": icon337,
  "database": icon338,
  "date-time": icon339,
  "debug": icon340,
  "delete": icon341,
  "delete-sharp": icon342,
  "diamond-gem": icon343,
  "directions": icon344,
  "directions-sharp": icon345,
  "dock": icon346,
  "dock-sharp": icon347,
  "dog": icon348,
  "door-closed": icon349,
  "door-closed-sharp": icon350,
  "download": icon351,
  "download-sharp": icon352,
  "drum": icon353,
  "earth": icon354,
  "estate": icon355,
  "estate-sharp": icon356,
  "expand": icon357,
  "external-link": icon358,
  "external-link-sharp": icon359,
  "eye": icon360,
  "eye-off": icon361,
  "factory": icon362,
  "factory-sharp": icon363,
  "feather": icon364,
  "file": icon365,
  "file-sharp": icon366,
  "file-text": icon367,
  "file-text-sharp": icon368,
  "files": icon369,
  "files-sharp": icon370,
  "filter": icon371,
  "fire": icon372,
  "fish": icon373,
  "flag": icon374,
  "flatten": icon375,
  "flip-horizontal-2": icon376,
  "flip-vertical-2": icon377,
  "float-center": icon378,
  "float-center-sharp": icon379,
  "float-left": icon380,
  "float-left-sharp": icon381,
  "float-right": icon382,
  "float-right-sharp": icon383,
  "folder": icon384,
  "folder-plus": icon385,
  "folder-plus-sharp": icon386,
  "folder-sharp": icon387,
  "forward": icon388,
  "forward-sharp": icon389,
  "frame": icon390,
  "frown": icon391,
  "gallery-thumbnails": icon392,
  "gallery-thumbnails-sharp": icon393,
  "gamepad": icon394,
  "gamepad-sharp": icon395,
  "gift": icon396,
  "gift-sharp": icon397,
  "git-branch": icon398,
  "git-branch-sharp": icon399,
  "git-commit": icon400,
  "git-commit-sharp": icon401,
  "git-merge": icon402,
  "git-merge-sharp": icon403,
  "git-pull-request": icon404,
  "git-pull-request-sharp": icon405,
  "globe": icon406,
  "goal": icon407,
  "gps": icon408,
  "gps-2": icon409,
  "gps-2-sharp": icon410,
  "gps-sharp": icon411,
  "gpu": icon412,
  "gpu-sharp": icon413,
  "grid-2x2-2": icon414,
  "grid-2x2-2-sharp": icon415,
  "grid-2x3": icon416,
  "grid-2x3-sharp": icon417,
  "grid-3x2": icon418,
  "grid-3x2-sharp": icon419,
  "grid-3x3": icon420,
  "grid-3x3-sharp": icon421,
  "hand": icon422,
  "handbag": icon423,
  "handbag-sharp": icon424,
  "hash": icon425,
  "heading": icon426,
  "heading-1": icon427,
  "heading-2": icon428,
  "heading-3": icon429,
  "heading-4": icon430,
  "heading-5": icon431,
  "heading-6": icon432,
  "headphone": icon433,
  "heart": icon434,
  "helicopter": icon435,
  "home": icon436,
  "home-sharp": icon437,
  "hotel-bed": icon438,
  "hotel-bed-sharp": icon439,
  "human": icon440,
  "human-arms-down": icon441,
  "human-arms-up": icon442,
  "icon-category": icon443,
  "icons": icon444,
  "image": icon445,
  "image-2-plus": icon446,
  "image-2-plus-sharp": icon447,
  "image-new": icon448,
  "image-new-sharp": icon449,
  "image-sharp": icon450,
  "images": icon451,
  "images-sharp": icon452,
  "inbox": icon453,
  "inbox-sharp": icon454,
  "info-box": icon455,
  "info-box-sharp": icon456,
  "invert": icon457,
  "invert-sharp": icon458,
  "invoice": icon459,
  "invoice-sharp": icon460,
  "joystick": icon461,
  "joystick-sharp": icon462,
  "keyboard-music": icon463,
  "keyboard-music-sharp": icon464,
  "languages": icon465,
  "languages-sharp": icon466,
  "lasso": icon467,
  "laugh": icon468,
  "laugh-sharp": icon469,
  "leaf": icon470,
  "letter-a": icon471,
  "letter-a-circle": icon472,
  "letter-b": icon473,
  "letter-b-circle": icon474,
  "letter-c": icon475,
  "letter-c-circle": icon476,
  "letter-d": icon477,
  "letter-d-circle": icon478,
  "letter-e": icon479,
  "letter-e-circle": icon480,
  "letter-f": icon481,
  "letter-f-circle": icon482,
  "letter-g": icon483,
  "letter-g-circle": icon484,
  "letter-h": icon485,
  "letter-h-circle": icon486,
  "letter-i": icon487,
  "letter-i-circle": icon488,
  "letter-j": icon489,
  "letter-j-circle": icon490,
  "letter-k": icon491,
  "letter-k-circle": icon492,
  "letter-l": icon493,
  "letter-l-circle": icon494,
  "letter-m": icon495,
  "letter-m-circle": icon496,
  "letter-n": icon497,
  "letter-n-circle": icon498,
  "letter-o": icon499,
  "letter-o-circle": icon500,
  "letter-p": icon501,
  "letter-p-circle": icon502,
  "letter-q": icon503,
  "letter-q-circle": icon504,
  "letter-r": icon505,
  "letter-r-circle": icon506,
  "letter-s": icon507,
  "letter-s-circle": icon508,
  "letter-t": icon509,
  "letter-t-circle": icon510,
  "letter-u": icon511,
  "letter-u-circle": icon512,
  "letter-v": icon513,
  "letter-v-circle": icon514,
  "letter-w": icon515,
  "letter-w-circle": icon516,
  "letter-x": icon517,
  "letter-x-circle": icon518,
  "letter-y": icon519,
  "letter-y-circle": icon520,
  "letter-z": icon521,
  "letter-z-circle": icon522,
  "library": icon523,
  "lightbulb": icon524,
  "lightbulb-off": icon525,
  "link": icon526,
  "link-sharp": icon527,
  "list-box": icon528,
  "list-box-sharp": icon529,
  "loader": icon530,
  "loading": icon531,
  "loading-2": icon532,
  "loading-3": icon533,
  "lock": icon534,
  "lock-sharp": icon535,
  "login": icon536,
  "login-sharp": icon537,
  "logout": icon538,
  "logout-sharp": icon539,
  "magic-edit": icon540,
  "mail": icon541,
  "mail-open": icon542,
  "mail-open-sharp": icon543,
  "mail-right": icon544,
  "mail-right-sharp": icon545,
  "mail-sharp": icon546,
  "mailbox": icon547,
  "mailbox-sharp": icon548,
  "map-pin": icon549,
  "map-pin-home": icon550,
  "megaphone": icon551,
  "megaphone-sharp": icon552,
  "meh": icon553,
  "meh-sharp": icon554,
  "membercard": icon555,
  "membercard-sharp": icon556,
  "memory-stick": icon557,
  "memory-stick-sharp": icon558,
  "menu": icon559,
  "menu-circle": icon560,
  "menu-square": icon561,
  "menu-square-sharp": icon562,
  "message": icon563,
  "message-sharp": icon564,
  "message-text": icon565,
  "message-text-sharp": icon566,
  "mic": icon567,
  "mic-off": icon568,
  "mic-off-sharp": icon569,
  "mic-sharp": icon570,
  "minus": icon571,
  "minus-box": icon572,
  "minus-box-sharp": icon573,
  "modem": icon574,
  "modem-sharp": icon575,
  "money": icon576,
  "money-sharp": icon577,
  "monitor": icon578,
  "monitor-sharp": icon579,
  "moon": icon580,
  "more-horizontal": icon581,
  "more-horizontal-sharp": icon582,
  "more-vertical": icon583,
  "more-vertical-sharp": icon584,
  "mouse": icon585,
  "music": icon586,
  "music-sharp": icon587,
  "note": icon588,
  "note-sharp": icon589,
  "notebook": icon590,
  "notebook-sharp": icon591,
  "notes": icon592,
  "notes-sharp": icon593,
  "open": icon594,
  "open-sharp": icon595,
  "package": icon596,
  "parking": icon597,
  "parking-off": icon598,
  "parking-off-sharp": icon599,
  "parking-sharp": icon600,
  "party-popper": icon601,
  "pc-case": icon602,
  "pc-case-sharp": icon603,
  "pen-square": icon604,
  "pen-square-sharp": icon605,
  "pencil": icon606,
  "phone": icon607,
  "phone-call": icon608,
  "phone-call-sharp": icon609,
  "phone-outgoing": icon610,
  "phone-outgoing-sharp": icon611,
  "phone-sharp": icon612,
  "pi": icon613,
  "pi-circle": icon614,
  "picture-in-picture": icon615,
  "picture-in-picture-sharp": icon616,
  "pipette": icon617,
  "pixelarticons": icon618,
  "play": icon619,
  "plus": icon620,
  "plus-box": icon621,
  "plus-box-sharp": icon622,
  "pointer": icon623,
  "potion": icon624,
  "potion-sharp": icon625,
  "pound": icon626,
  "power": icon627,
  "power-off": icon628,
  "presentation": icon629,
  "presentation-sharp": icon630,
  "printer": icon631,
  "printer-minimal-sharp": icon632,
  "projector": icon633,
  "proportions": icon634,
  "proportions-sharp": icon635,
  "quote-text-inline": icon636,
  "radio": icon637,
  "radius": icon638,
  "ratio": icon639,
  "receipt": icon640,
  "receipt-sharp": icon641,
  "recycle": icon642,
  "redo": icon643,
  "redo-sharp": icon644,
  "reload": icon645,
  "reload-sharp": icon646,
  "repeat": icon647,
  "repeat-sharp": icon648,
  "road-sign": icon649,
  "robot": icon650,
  "robot-face": icon651,
  "robot-face-happy": icon652,
  "robot-face-happy-sharp": icon653,
  "robot-face-sad": icon654,
  "robot-face-sad-sharp": icon655,
  "robot-face-sharp": icon656,
  "robot-sharp": icon657,
  "rss": icon658,
  "rss-circle": icon659,
  "rss-square": icon660,
  "rss-square-sharp": icon661,
  "rubel": icon662,
  "save": icon663,
  "save-sharp": icon664,
  "scale": icon665,
  "scan-barcode": icon666,
  "scan-barcode-sharp": icon667,
  "scissors": icon668,
  "scissors-sharp": icon669,
  "script": icon670,
  "script-sharp": icon671,
  "scroll-horizontal": icon672,
  "scroll-vertical": icon673,
  "search": icon674,
  "section": icon675,
  "section-copy": icon676,
  "section-minus": icon677,
  "section-plus": icon678,
  "section-x": icon679,
  "send": icon680,
  "server": icon681,
  "server-sharp": icon682,
  "settings-2": icon683,
  "settings-2-sharp": icon684,
  "settings-cog": icon685,
  "settings-cog-2": icon686,
  "shapes": icon687,
  "share": icon688,
  "share-sharp": icon689,
  "shield": icon690,
  "shield-sharp": icon691,
  "ship": icon692,
  "shirt": icon693,
  "shirt-sharp": icon694,
  "shopping-bag": icon695,
  "shopping-bag-sharp": icon696,
  "shopping-cart": icon697,
  "shuffle": icon698,
  "shuffle-sharp": icon699,
  "signal": icon700,
  "siren": icon701,
  "siren-off": icon702,
  "siren-off-sharp": icon703,
  "siren-sharp": icon704,
  "skull": icon705,
  "skull-sharp": icon706,
  "smart-home": icon707,
  "smart-home-sharp": icon708,
  "smartphone": icon709,
  "smartphone-sharp": icon710,
  "smile": icon711,
  "smile-sharp": icon712,
  "snail": icon713,
  "snake": icon714,
  "sofa": icon715,
  "sofa-sharp": icon716,
  "sort-horizontal": icon717,
  "sort-vertical": icon718,
  "sparkle": icon719,
  "sparkles": icon720,
  "speed-fast": icon721,
  "speed-medium": icon722,
  "speed-slow": icon723,
  "spline-cursor": icon724,
  "spotlight": icon725,
  "spotlight-sharp": icon726,
  "spray": icon727,
  "spray-can": icon728,
  "spray-image": icon729,
  "spray-wave": icon730,
  "square": icon731,
  "square-alert": icon732,
  "square-alert-sharp": icon733,
  "square-chevron-down": icon734,
  "square-chevron-down-sharp": icon735,
  "square-chevron-left": icon736,
  "square-chevron-left-sharp": icon737,
  "square-chevron-right": icon738,
  "square-chevron-right-sharp": icon739,
  "square-chevron-up": icon740,
  "square-chevron-up-sharp": icon741,
  "square-cursor": icon742,
  "square-cursor-sharp": icon743,
  "square-dashed-cursor": icon744,
  "square-dashed-cursor-sharp": icon745,
  "square-power": icon746,
  "square-power-sharp": icon747,
  "square-scissors": icon748,
  "square-scissors-sharp": icon749,
  "square-sharp": icon750,
  "star": icon751,
  "sticker": icon752,
  "sticker-sharp": icon753,
  "sticky-note": icon754,
  "sticky-note-sharp": icon755,
  "sticky-note-text": icon756,
  "sticky-note-text-sharp": icon757,
  "store": icon758,
  "store-sharp": icon759,
  "subscriptions": icon760,
  "subscriptions-sharp": icon761,
  "suitcase": icon762,
  "suitcase-sharp": icon763,
  "sunglasses": icon764,
  "sunglasses-sharp": icon765,
  "switch": icon766,
  "sword": icon767,
  "t-arrow-down": icon768,
  "t-arrow-up": icon769,
  "t-rex": icon770,
  "tab": icon771,
  "tab-sharp": icon772,
  "tablet": icon773,
  "tablet-sharp": icon774,
  "tangent": icon775,
  "target": icon776,
  "tea": icon777,
  "tea-sharp": icon778,
  "teach": icon779,
  "teach-sharp": icon780,
  "tent": icon781,
  "terminal": icon782,
  "terminal-sharp": icon783,
  "test-tube": icon784,
  "test-tube-sharp": icon785,
  "text-align-center": icon786,
  "text-align-center-box": icon787,
  "text-align-center-box-sharp": icon788,
  "text-align-justify": icon789,
  "text-align-justify-box": icon790,
  "text-align-justify-box-sharp": icon791,
  "text-align-left": icon792,
  "text-align-left-box": icon793,
  "text-align-left-box-sharp": icon794,
  "text-align-right": icon795,
  "text-align-right-box": icon796,
  "text-align-right-box-sharp": icon797,
  "text-colums": icon798,
  "text-cursor": icon799,
  "text-cursor-input": icon800,
  "text-cursor-input-sharp": icon801,
  "text-start-a": icon802,
  "text-start-a-sharp": icon803,
  "text-start-t": icon804,
  "text-wrap": icon805,
  "text-wrap-sharp": icon806,
  "thermometer": icon807,
  "thermometer-sharp": icon808,
  "thumbs-down": icon809,
  "thumbs-down-sharp": icon810,
  "thumbs-up": icon811,
  "thumbs-up-sharp": icon812,
  "toke-circle": icon813,
  "toke-square": icon814,
  "toke-square-sharp": icon815,
  "tool-case": icon816,
  "tool-case-sharp": icon817,
  "tournament": icon818,
  "tournament-sharp": icon819,
  "trash": icon820,
  "trash-sharp": icon821,
  "tree": icon822,
  "tree-pine": icon823,
  "trophy": icon824,
  "trophy-sharp": icon825,
  "truck": icon826,
  "truck-sharp": icon827,
  "tv": icon828,
  "tv-sharp": icon829,
  "undo": icon830,
  "undo-sharp": icon831,
  "university": icon832,
  "university-sharp": icon833,
  "unlink": icon834,
  "unlink-sharp": icon835,
  "unlock": icon836,
  "unlock-sharp": icon837,
  "upload": icon838,
  "upload-sharp": icon839,
  "user": icon840,
  "user-minus": icon841,
  "user-minus-sharp": icon842,
  "user-plus": icon843,
  "user-plus-sharp": icon844,
  "user-sharp": icon845,
  "user-x": icon846,
  "user-x-sharp": icon847,
  "users": icon848,
  "users-sharp": icon849,
  "utility-pole": icon850,
  "vibrate": icon851,
  "vibrate-sharp": icon852,
  "video": icon853,
  "video-sharp": icon854,
  "volume": icon855,
  "volume-1": icon856,
  "volume-2": icon857,
  "volume-3": icon858,
  "wall": icon859,
  "wall-sharp": icon860,
  "wallet": icon861,
  "wallet-sharp": icon862,
  "warehouse": icon863,
  "warning-diamond": icon864,
  "waves": icon865,
  "waves-arrow-down": icon866,
  "waves-arrow-up": icon867,
  "webcam": icon868,
  "wifi": icon869,
  "wind": icon870,
  "window-frame": icon871,
  "window-frame-sharp": icon872,
  "zap": icon873,
  "zap-off": icon874,
  "zoom-in": icon875,
  "zoom-out": icon876
} satisfies Record<IconName, string>;
