import { readdir, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const sourceDir = path.join(root, 'node_modules', 'pixelarticons', 'svg');
const namesOutput = path.join(root, 'src', 'lib', 'icons', 'icon-names.generated.ts');
const assetsOutput = path.join(root, 'src', 'lib', 'icons', 'pixel-icon-assets.generated.ts');

async function main() {
  const names = (await readdir(sourceDir, { withFileTypes: true }))
    .filter((entry) => entry.isFile() && entry.name.endsWith('.svg'))
    .map((entry) => entry.name.slice(0, -4))
    .sort((a, b) => a.localeCompare(b));

  if (names.length === 0) {
    throw new Error(`No pixelarticons SVG files found in ${sourceDir}`);
  }

  const generatedHeader = '// Generated by npm run icons:generate. Do not edit by hand.\n';
  const namesSource = `${generatedHeader}export const ALL_ICON_NAMES = ${JSON.stringify(names, null, 2)} as const;\n`;
  const imports = names.map((name, index) =>
    `import icon${index} from 'pixelarticons/svg/${name}.svg?url';`
  );
  const entries = names.map((name, index) => `  ${JSON.stringify(name)}: icon${index}`);
  const assetsSource = `${generatedHeader}${imports.join('\n')}\n\n` +
    `import type { IconName } from './icon-names';\n\n` +
    `export const PIXEL_ICON_ASSETS = {\n${entries.join(',\n')}\n} satisfies Record<IconName, string>;\n`;

  await Promise.all([
    writeFile(namesOutput, namesSource),
    writeFile(assetsOutput, assetsSource)
  ]);

  console.log(`Generated ${names.length} pixelarticons.`);
}

main().catch((error) => {
  console.error(error);
  process.exitCode = 1;
});
